name: HomeBase
version: '1.3-SNAPSHOT'
main: dev.jaegyu.homeBase.HomeBase
description: HomeBase plugin
api-version: '1.21'
authors: [ JaegyuDev ]
website: https://github.com/JaegyuDev/LazyLoader
bootstrapper: dev.jaegyu.homeBase.HomeBaseBootstrap