name: HomeBase
version: '1.3-SNAPSHOT'
main: dev.jaegyu.homeBase.HomeBase
api-version: '1.21'
authors: [ JaegyuDev ]
website: https://github.com/JaegyuDev/LazyLoader
commands:
  home:
    description: Teleports you to your respawn location
    usage: /home

  hb:
    description: HomeBase admin commands
    usage: /hb <subcommand>
    permission: homebase.admin

permissions:
  homebase.admin:
    description: Access to HomeBase admin commands
    default: op